import Head from 'next/head'
import { canSSRAuth } from '../utils/canSSRAuth'
import Header from '../components/header'
import BalanceContainer from '../components/balance'
import History from '../components/history'
import { setupAPIClient } from '../services/api'
export default function Balance({cashIn,cashOut}) {
    return (
      <div >
      
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        <main >
        
          <BalanceContainer/>
          <History cashIn={cashIn} cashOut={cashOut}/>
        </main>
      </div>
    )
  }
  export const getServerSideProps= canSSRAuth(async(ctx)=>{
    const apiClient = setupAPIClient(ctx)
    const response = await apiClient.get("/user/transactions")
    const{cashIn,cashOut}=response.data
    return{
      props:{
        cashIn,
        cashOut
      }
    }
  })
    
  